services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - capas_data:/app/static/capas
    networks:
      - edge
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=edge"
      - "traefik.http.routers.livropedia-api.entrypoints=app-livropedia-api"
      - "traefik.http.routers.livropedia-api.rule=Host(`srv1892430.hstgr.cloud`)"
      - "traefik.http.routers.livropedia-api.tls.certresolver=le"
      - "traefik.http.services.livropedia-api.loadbalancer.server.port=5001"

networks:
  edge:
    external: true
  db:
    external: true

volumes:
  capas_data:
