"""livro_externo_cache

Revision ID: 9ac41b599133
Revises: 621225a5f2b3
Create Date: 2026-08-08 12:13:50.690041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac41b599133'
down_revision = '621225a5f2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro_externo_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('autor', sa.String(length=200), nullable=True),
    sa.Column('capa_url', sa.String(length=250), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('ano_publicacao', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', name='uq_livro_externo_cache_external_id')
    )
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_livro_external_id'))
        batch_op.create_unique_constraint('uq_livro_external_id', ['external_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.drop_constraint('uq_livro_external_id', type_='unique')
        batch_op.create_index(batch_op.f('uq_livro_external_id'), ['external_id'], unique=1)

    op.drop_table('livro_externo_cache')
    # ### end Alembic commands ###
